//------------------------------------------------------------------------------
// <auto-generated>
// 	This code was auto-generated by Crockhead.Table
// 	version 0.0.2
// 	update 2025-12-13 10:17:23
// </auto-generated>
//------------------------------------------------------------------------------
using Crockhead.Core;
using Crockhead.Table;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using MillenniumOfCultivation;
using MillenniumOfCultivation.Battle;


namespace MillenniumOfCultivation
{
	/// <summary>
	/// BookTable Recordable Data.
	/// </summary>
	[JsonObject(MemberSerialization.OptIn)]
	public class BookTableRecord : IRecordable
	{
		/// <summary>
		/// Id.
		/// </summary>
		[JsonProperty]
		public int Id { set; get; }
		
		/// <summary>
		/// Name.
		/// </summary>
		[JsonProperty]
		public string Name { set; get; }
		
		/// <summary>
		/// GradeType.
		/// </summary>
		[JsonProperty]
		public int GradeType { set; get; }
		
		/// <summary>
		/// BookType.
		/// </summary>
		[JsonProperty]
		public int BookType { set; get; }
		
		/// <summary>
		/// Gold.
		/// </summary>
		[JsonProperty]
		public int Gold { set; get; }
		
		/// <summary>
		/// Explain.
		/// </summary>
		[JsonProperty]
		public string Explain { set; get; }
		
		/// <summary>
		/// IconId.
		/// </summary>
		[JsonProperty]
		public int IconId { set; get; }
		
		/// <summary>
		/// Description.
		/// </summary>
		[JsonProperty]
		public string Description { set; get; }
		
		/// <summary>
		/// 필드 갯수.
		/// </summary>
		int IRecordable.GetFieldCount()
		{
			return 8;
		}
		
		/// <summary>
		/// 필드 이름.
		/// </summary>
		string IRecordable.GetFieldName(int index)
		{
			switch (index)
			{
				case 0: return "Id";
				case 1: return "Name";
				case 2: return "GradeType";
				case 3: return "BookType";
				case 4: return "Gold";
				case 5: return "Explain";
				case 6: return "IconId";
				case 7: return "Description";
				default: return string.Empty;
			}
		}
		
		/// <summary>
		/// 필드 타입.
		/// </summary>
		Type IRecordable.GetFieldType(int index)
		{
			switch (index)
			{
				case 0: return Id.GetType();
				case 1: return Name.GetType();
				case 2: return GradeType.GetType();
				case 3: return BookType.GetType();
				case 4: return Gold.GetType();
				case 5: return Explain.GetType();
				case 6: return IconId.GetType();
				case 7: return Description.GetType();
				default: return null;
			}
		}
		
		/// <summary>
		/// 필드 값.
		/// </summary>
		object IRecordable.GetFieldValue(int index)
		{
			switch (index)
			{
				case 0: return Id;
				case 1: return Name;
				case 2: return GradeType;
				case 3: return BookType;
				case 4: return Gold;
				case 5: return Explain;
				case 6: return IconId;
				case 7: return Description;
				default: return null;
			}
		}
	}
}
