//------------------------------------------------------------------------------
// <auto-generated>
// 	This code was auto-generated by Crockhead.Table
// 	version 0.0.1
// 	update 2025-11-14 12:23:21
// </auto-generated>
//------------------------------------------------------------------------------
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using Crockhead.Table;
using MillenniumOfCultivation.Battle;


/// <summary>
/// CardTable Recordable Data.
/// </summary>
[JsonObject(MemberSerialization.OptIn)]
public class CardTableRecord : IRecordable
{
	/// <summary>
	/// Id.
	/// </summary>
	[JsonProperty]
	public int Id { set; get; }

	/// <summary>
	/// Name.
	/// </summary>
	[JsonProperty]
	public string Name { set; get; }

	/// <summary>
	/// CardType.
	/// </summary>
	[JsonProperty]
	public CardType CardType { set; get; }

	/// <summary>
	/// Grade.
	/// </summary>
	[JsonProperty]
	public GradeType Grade { set; get; }

	/// <summary>
	/// ActionType.
	/// </summary>
	[JsonProperty]
	public CardActionType ActionType { set; get; }

	/// <summary>
	/// ActionTarget.
	/// </summary>
	[JsonProperty]
	public CardTargetType ActionTarget { set; get; }

	/// <summary>
	/// ActionSkillTableId.
	/// </summary>
	[JsonProperty]
	public int ActionSkillTableId { set; get; }

	/// <summary>
	/// CostAP.
	/// </summary>
	[JsonProperty]
	public int CostAP { set; get; }

	/// <summary>
	/// Description.
	/// </summary>
	[JsonProperty]
	public string Description { set; get; }

	/// <summary>
	/// 필드 갯수.
	/// </summary>
	int IRecordable.GetFieldCount()
	{
		return 9;
	}

	/// <summary>
	/// 필드 이름.
	/// </summary>
	string IRecordable.GetFieldName(int index)
	{
		switch (index)
		{
			case 0: return "Id";
			case 1: return "Name";
			case 2: return "CardType";
			case 3: return "Grade";
			case 4: return "ActionType";
			case 5: return "ActionTarget";
			case 6: return "ActionSkillTableId";
			case 7: return "CostAP";
			case 8: return "Description";
			default: return string.Empty;
		}
	}

	/// <summary>
	/// 필드 타입.
	/// </summary>
	Type IRecordable.GetFieldType(int index)
	{
		switch (index)
		{
			case 0: return Id.GetType();
			case 1: return Name.GetType();
			case 2: return CardType.GetType();
			case 3: return Grade.GetType();
			case 4: return ActionType.GetType();
			case 5: return ActionTarget.GetType();
			case 6: return ActionSkillTableId.GetType();
			case 7: return CostAP.GetType();
			case 8: return Description.GetType();
			default: return null;
		}
	}

	/// <summary>
	/// 필드 값.
	/// </summary>
	object IRecordable.GetFieldValue(int index)
	{
		switch (index)
		{
			case 0: return Id;
			case 1: return Name;
			case 2: return CardType;
			case 3: return Grade;
			case 4: return ActionType;
			case 5: return ActionTarget;
			case 6: return ActionSkillTableId;
			case 7: return CostAP;
			case 8: return Description;
			default: return null;
		}
	}
}