//------------------------------------------------------------------------------
// <auto-generated>
// 	This code was auto-generated by Crockhead.Table
// 	version 0.0.2
// 	update 2025-12-13 10:17:23
// </auto-generated>
//------------------------------------------------------------------------------
using Crockhead.Core;
using Crockhead.Table;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using MillenniumOfCultivation;
using MillenniumOfCultivation.Battle;


namespace MillenniumOfCultivation
{
	/// <summary>
	/// DialogTable Recordable Data.
	/// </summary>
	[JsonObject(MemberSerialization.OptIn)]
	public class DialogTableRecord : IRecordable
	{
		/// <summary>
		/// Id.
		/// </summary>
		[JsonProperty]
		public int Id { set; get; }
		
		/// <summary>
		/// Group.
		/// </summary>
		[JsonProperty]
		public int Group { set; get; }
		
		/// <summary>
		/// PortraitId.
		/// </summary>
		[JsonProperty]
		public int PortraitId { set; get; }
		
		/// <summary>
		/// Type.
		/// </summary>
		[JsonProperty]
		public int Type { set; get; }
		
		/// <summary>
		/// Value.
		/// </summary>
		[JsonProperty]
		public string Value { set; get; }
		
		/// <summary>
		/// 필드 갯수.
		/// </summary>
		int IRecordable.GetFieldCount()
		{
			return 5;
		}
		
		/// <summary>
		/// 필드 이름.
		/// </summary>
		string IRecordable.GetFieldName(int index)
		{
			switch (index)
			{
				case 0: return "Id";
				case 1: return "Group";
				case 2: return "PortraitId";
				case 3: return "Type";
				case 4: return "Value";
				default: return string.Empty;
			}
		}
		
		/// <summary>
		/// 필드 타입.
		/// </summary>
		Type IRecordable.GetFieldType(int index)
		{
			switch (index)
			{
				case 0: return Id.GetType();
				case 1: return Group.GetType();
				case 2: return PortraitId.GetType();
				case 3: return Type.GetType();
				case 4: return Value.GetType();
				default: return null;
			}
		}
		
		/// <summary>
		/// 필드 값.
		/// </summary>
		object IRecordable.GetFieldValue(int index)
		{
			switch (index)
			{
				case 0: return Id;
				case 1: return Group;
				case 2: return PortraitId;
				case 3: return Type;
				case 4: return Value;
				default: return null;
			}
		}
	}
}
