//------------------------------------------------------------------------------
// <auto-generated>
// 	This code was auto-generated by Crockhead.Table
// 	version 0.0.2
// 	update 2025-12-08 11:47:35
// </auto-generated>
//------------------------------------------------------------------------------
using Crockhead.Core;
using Crockhead.Table;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using MillenniumOfCultivation;
using MillenniumOfCultivation.Battle;


namespace MillenniumOfCultivation
{
	/// <summary>
	/// ItemTable Recordable Data.
	/// </summary>
	[JsonObject(MemberSerialization.OptIn)]
	public class ItemTableRecord : IRecordable
	{
		/// <summary>
		/// Id.
		/// </summary>
		[JsonProperty]
		public int Id { set; get; }
		
		/// <summary>
		/// Name.
		/// </summary>
		[JsonProperty]
		public string Name { set; get; }
		
		/// <summary>
		/// StatList.
		/// </summary>
		[JsonProperty]
		public FloatDictionary StatList { set; get; }
		
		/// <summary>
		/// Description.
		/// </summary>
		[JsonProperty]
		public string Description { set; get; }
		
			/// <summary>
			/// 필드 갯수.
			/// </summary>
			int IRecordable.GetFieldCount()
			{
				return 4;
			}
			
			/// <summary>
			/// 필드 이름.
			/// </summary>
			string IRecordable.GetFieldName(int index)
			{
				switch (index)
				{
					case 0: return "Id";
					case 1: return "Name";
					case 2: return "StatList";
					case 3: return "Description";
					default: return string.Empty;
				}
			}
			
			/// <summary>
			/// 필드 타입.
			/// </summary>
			Type IRecordable.GetFieldType(int index)
			{
				switch (index)
				{
					case 0: return Id.GetType();
					case 1: return Name.GetType();
					case 2: return StatList.GetType();
					case 3: return Description.GetType();
					default: return null;
				}
			}
			
			/// <summary>
			/// 필드 값.
			/// </summary>
			object IRecordable.GetFieldValue(int index)
			{
				switch (index)
				{
					case 0: return Id;
					case 1: return Name;
					case 2: return StatList;
					case 3: return Description;
					default: return null;
				}
			}
		}
	}
