//------------------------------------------------------------------------------
// <auto-generated>
// 	This code was auto-generated by Crockhead.Table
// 	version 0.0.2
// 	update 2025-12-11 16:52:57
// </auto-generated>
//------------------------------------------------------------------------------
using Crockhead.Core;
using Crockhead.Table;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using MillenniumOfCultivation;
using MillenniumOfCultivation.Battle;


namespace MillenniumOfCultivation
{
	/// <summary>
	/// MaterialTable Recordable Data.
	/// </summary>
	[JsonObject(MemberSerialization.OptIn)]
	public class MaterialTableRecord : IRecordable
	{
		/// <summary>
		/// Id.
		/// </summary>
		[JsonProperty]
		public int Id { set; get; }
		
		/// <summary>
		/// Name.
		/// </summary>
		[JsonProperty]
		public string Name { set; get; }
		
		/// <summary>
		/// ItemType.
		/// </summary>
		[JsonProperty]
		public int ItemType { set; get; }
		
		/// <summary>
		/// MaterialType.
		/// </summary>
		[JsonProperty]
		public string MaterialType { set; get; }
		
		/// <summary>
		/// Icon.
		/// </summary>
		[JsonProperty]
		public string Icon { set; get; }
		
		/// <summary>
		/// Description.
		/// </summary>
		[JsonProperty]
		public string Description { set; get; }
		
		/// <summary>
		/// 필드 갯수.
		/// </summary>
		int IRecordable.GetFieldCount()
		{
			return 6;
		}
		
		/// <summary>
		/// 필드 이름.
		/// </summary>
		string IRecordable.GetFieldName(int index)
		{
			switch (index)
			{
				case 0: return "Id";
				case 1: return "Name";
				case 2: return "ItemType";
				case 3: return "MaterialType";
				case 4: return "Icon";
				case 5: return "Description";
				default: return string.Empty;
			}
		}
		
		/// <summary>
		/// 필드 타입.
		/// </summary>
		Type IRecordable.GetFieldType(int index)
		{
			switch (index)
			{
				case 0: return Id.GetType();
				case 1: return Name.GetType();
				case 2: return ItemType.GetType();
				case 3: return MaterialType.GetType();
				case 4: return Icon.GetType();
				case 5: return Description.GetType();
				default: return null;
			}
		}
		
		/// <summary>
		/// 필드 값.
		/// </summary>
		object IRecordable.GetFieldValue(int index)
		{
			switch (index)
			{
				case 0: return Id;
				case 1: return Name;
				case 2: return ItemType;
				case 3: return MaterialType;
				case 4: return Icon;
				case 5: return Description;
				default: return null;
			}
		}
	}
}
