//------------------------------------------------------------------------------
// <auto-generated>
// 	This code was auto-generated by Crockhead.Table
// 	version 0.0.1
// 	update 2025-11-14 12:23:21
// </auto-generated>
//------------------------------------------------------------------------------
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using Crockhead.Table;


/// <summary>
/// MinionTable Recordable Data.
/// </summary>
[JsonObject(MemberSerialization.OptIn)]
public class MinionTableRecord : IRecordable
{
	/// <summary>
	/// Id.
	/// </summary>
	[JsonProperty]
	public int Id { set; get; }

	/// <summary>
	/// Name.
	/// </summary>
	[JsonProperty]
	public string Name { set; get; }

	/// <summary>
	/// 필드 갯수.
	/// </summary>
	int IRecordable.GetFieldCount()
	{
		return 2;
	}

	/// <summary>
	/// 필드 이름.
	/// </summary>
	string IRecordable.GetFieldName(int index)
	{
		switch (index)
		{
			case 0: return "Id";
			case 1: return "Name";
			default: return string.Empty;
		}
	}

	/// <summary>
	/// 필드 타입.
	/// </summary>
	Type IRecordable.GetFieldType(int index)
	{
		switch (index)
		{
			case 0: return Id.GetType();
			case 1: return Name.GetType();
			default: return null;
		}
	}

	/// <summary>
	/// 필드 값.
	/// </summary>
	object IRecordable.GetFieldValue(int index)
	{
		switch (index)
		{
			case 0: return Id;
			case 1: return Name;
			default: return null;
		}
	}
}