//------------------------------------------------------------------------------
// <auto-generated>
// 	This code was auto-generated by Crockhead.Table
// 	version 0.0.2
// 	update 2025-12-13 10:17:23
// </auto-generated>
//------------------------------------------------------------------------------
using Crockhead.Core;
using Crockhead.Table;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using MillenniumOfCultivation;
using MillenniumOfCultivation.Battle;


namespace MillenniumOfCultivation
{
	/// <summary>
	/// PortraitTable Recordable Data.
	/// </summary>
	[JsonObject(MemberSerialization.OptIn)]
	public class PortraitTableRecord : IRecordable
	{
		/// <summary>
		/// Id.
		/// </summary>
		[JsonProperty]
		public int Id { set; get; }
		
		/// <summary>
		/// Name.
		/// </summary>
		[JsonProperty]
		public string Name { set; get; }
		
		/// <summary>
		/// TexturePath.
		/// </summary>
		[JsonProperty]
		public string TexturePath { set; get; }
		
		/// <summary>
		/// Color.
		/// </summary>
		[JsonProperty]
		public string Color { set; get; }
		
		/// <summary>
		/// Introduction.
		/// </summary>
		[JsonProperty]
		public string Introduction { set; get; }
		
		/// <summary>
		/// 필드 갯수.
		/// </summary>
		int IRecordable.GetFieldCount()
		{
			return 5;
		}
		
		/// <summary>
		/// 필드 이름.
		/// </summary>
		string IRecordable.GetFieldName(int index)
		{
			switch (index)
			{
				case 0: return "Id";
				case 1: return "Name";
				case 2: return "TexturePath";
				case 3: return "Color";
				case 4: return "Introduction";
				default: return string.Empty;
			}
		}
		
		/// <summary>
		/// 필드 타입.
		/// </summary>
		Type IRecordable.GetFieldType(int index)
		{
			switch (index)
			{
				case 0: return Id.GetType();
				case 1: return Name.GetType();
				case 2: return TexturePath.GetType();
				case 3: return Color.GetType();
				case 4: return Introduction.GetType();
				default: return null;
			}
		}
		
		/// <summary>
		/// 필드 값.
		/// </summary>
		object IRecordable.GetFieldValue(int index)
		{
			switch (index)
			{
				case 0: return Id;
				case 1: return Name;
				case 2: return TexturePath;
				case 3: return Color;
				case 4: return Introduction;
				default: return null;
			}
		}
	}
}
