//------------------------------------------------------------------------------
// <auto-generated>
// 	This code was auto-generated by Crockhead.Table
// 	version 0.0.2
// 	update 2025-12-08 11:47:35
// </auto-generated>
//------------------------------------------------------------------------------
using Crockhead.Core;
using Crockhead.Table;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using MillenniumOfCultivation;
using MillenniumOfCultivation.Battle;


namespace MillenniumOfCultivation
{
	/// <summary>
	/// SoundTable Recordable Data.
	/// </summary>
	[JsonObject(MemberSerialization.OptIn)]
	public class SoundTableRecord : IRecordable
	{
		/// <summary>
		/// Id.
		/// </summary>
		[JsonProperty]
		public int Id { set; get; }
		
		/// <summary>
		/// Name.
		/// </summary>
		[JsonProperty]
		public string Name { set; get; }
		
		/// <summary>
		/// Type.
		/// </summary>
		[JsonProperty]
		public Crockhead.Unity.SoundType Type { set; get; }
		
		/// <summary>
		/// AssetPath.
		/// </summary>
		[JsonProperty]
		public string AssetPath { set; get; }
		
		/// <summary>
		/// Description.
		/// </summary>
		[JsonProperty]
		public string Description { set; get; }
		
			/// <summary>
			/// 필드 갯수.
			/// </summary>
			int IRecordable.GetFieldCount()
			{
				return 5;
			}
			
			/// <summary>
			/// 필드 이름.
			/// </summary>
			string IRecordable.GetFieldName(int index)
			{
				switch (index)
				{
					case 0: return "Id";
					case 1: return "Name";
					case 2: return "Type";
					case 3: return "AssetPath";
					case 4: return "Description";
					default: return string.Empty;
				}
			}
			
			/// <summary>
			/// 필드 타입.
			/// </summary>
			Type IRecordable.GetFieldType(int index)
			{
				switch (index)
				{
					case 0: return Id.GetType();
					case 1: return Name.GetType();
					case 2: return Type.GetType();
					case 3: return AssetPath.GetType();
					case 4: return Description.GetType();
					default: return null;
				}
			}
			
			/// <summary>
			/// 필드 값.
			/// </summary>
			object IRecordable.GetFieldValue(int index)
			{
				switch (index)
				{
					case 0: return Id;
					case 1: return Name;
					case 2: return Type;
					case 3: return AssetPath;
					case 4: return Description;
					default: return null;
				}
			}
		}
	}
